source 'https://rubygems.org'
gem 'rails', '~> 2.3.2'
gem 'mysql', '~> 2.8.1'
gem 'thinking-sphinx', '~> 1.4.14'
gem 'spreadsheet'
gem 'sanitize'
gem 'calendar_date_select'
gem 'will_paginate', '~> 2.3.16'
gem 'puma'
gem 'tzinfo', '~> 0.3.31'
