development:
  upload_directory: resumes
  temp_directory:   tmp
  temp_file:        temp_file
  file_size:        1048576
  number_positions: 15
  xls_temp_file:    xls_tmp
  zip_temp_file:    zip_tmp
  temp_resumes:     tmp_resumes
  status_file:      status
  host_name:        localhost:3000
  subdomain: 

test:
  upload_directory: resumes/test
  temp_directory:   tmp
  temp_file:        temp_file
  file_size:        1048576
  number_positions: 15
  xls_temp_file:    xls_tmp
  zip_temp_file:    zip_tmp
  temp_resumes:     tmp_resumes
  status_file:      status
  host_name:        localhost:3010
  subdomain: 

production:
  upload_directory: /apps/shared/resumes
  temp_directory:   /apps/shared/resumes
  temp_file:        temp_file
  file_size:        1048576
  number_positions: 15
  xls_temp_file:    xls_tmp
  zip_temp_file:    zip_tmp
  temp_resumes:     tmp_resumes
  status_file:      status
  host_name:        apps.mirafra.com/new-recruit
  subdomain:        /new-recruit
